spring:
  aop:
    proxy-target-class: true



security:
  user:
    password: none
  ignored:
    - "*.bundle.*"
  oauth2:
    client:
      accessTokenUri: http://localhost:8080/authorization-server/oauth/token
      userAuthorizationUri: http://localhost:8080/authorization-server/oauth/authorize
      clientId: web-client
      clientSecret: 12345678
    resource:
      jwk:
        key-set-uri: http://localhost:8080/authorization-server/.well-known/jwks.json



zuul:
  routes:
    resource:
      path: /resource_server/**
      url: http://localhost:8090/resource_server/hello
    user:
      path: /user/**
      url: http://localhost:8091/resource_server_2/user



logging:
  level:
    org.springframework.security: DEBUG
